env:
  global:
    - CI="travis"
    - MONGODB=3.6.6
before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --auth &> /dev/null &
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
  - mongod --version

before_script:
- nodejs --version
- mongod --version
- cat /var/log/mongodb/mongod.log
script: sudo npm test
after_script:
- cat /var/log/mongodb/mongod.log